---
title: "Yield Curve"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
---


```{r setup, message = FALSE}
library(quantmod)
library(tidyverse)
library(tibbletime)
library(highcharter)
options(digits = 3)
```

Sidebar {.sidebar}
=====================================
  
```{r}

fluidRow(
  column(7,
  dateInput("date", "Select Yield Curve Date", format = "yyyy-mm-dd", daysofweekdisabled=c(0,6), max =Sys.Date()-7))
)

fluidRow(
column(7,
             tags$br(actionButton("go", "Plot the Yield Curve")),
             tags$br())
       )
            
fluidRow(
  column(8,
  selectInput("term", "Select Term Spread",
              c("30 Year-3 Month",
                "10 Year-1 Year"))
  ))

fluidRow(
column(7,
             tags$br(actionButton("go1", "Plot the Term Spread")),
             tags$br())
       )

######### Yield #################################################

Build_Curve <- eventReactive(input$go, {
  
Yield=c("DGS3MO","DGS6MO","DGS1", "DGS2", "DGS3", "DGS5",  
        "DGS7",  
        "DGS10",  
        "DGS20",  
        "DGS30")

getSymbols(Yield, src = "FRED")

treasury=na.omit(merge(DGS3MO,DGS6MO,DGS1, DGS2, DGS3, DGS5,  
                       DGS7,  
                       DGS10,  
                       DGS20,  
                       DGS30))

treasury <-treasury %>%
  data.frame(Date = index(.))   %>%
  remove_rownames() %>%
  gather(TreasuryBond, Yields, -Date) %>%
  group_by(TreasuryBond)

Build_Curve=treasury %>%
  filter(Date==as.Date(input$date))
  
})


######### Spread ###############################################
Term_Spread <- eventReactive(input$go1, {

Yield1=c("DGS3MO","DGS6MO","DGS1", "DGS2", "DGS3", "DGS5",  
        "DGS7",  
        "DGS10",  
        "DGS20",  
        "DGS30")

getSymbols(Yield1, src = "FRED")  
  
  
  
  if (input$term=="30 Year-3 Month") {
    Term_Spread=na.omit(DGS30-DGS3MO)
  }
  
  else {
    Term_Spread=na.omit(DGS10-DGS1)
  }
  
  return(Term_Spread)
  
# Term_Spread=ifelse(input$term=FALSE, na.omit(DGS30-DGS3MO),
#                    na.omit(DGS10-DGS1))
  
  

})

```

Please Select Date for Yield Curve Plot, and Term Spread type
=====================================  


Row {.tabset .tabset-fade}
-------------------------------------


### Yield Curve

```{r}
renderPlot({
Build_Curve()%>%
  ggplot(aes(x = factor(TreasuryBond, levels =c("DGS3MO","DGS6MO","DGS1", "DGS2", "DGS3", "DGS5",  
                                                "DGS7",  
                                                "DGS10",  
                                                "DGS20",  
                                                "DGS30")), 
             y=Yields, group = 1)) +geom_line()+geom_point()+geom_text(aes(label = round(Yields, 3)),
                                                                         vjust = "outward", hjust = "inward",
                                                                         show.legend = FALSE)+
  xlab("Treasuries from 3 Month to 30 Years") +ylab("Yields in %")  
})
```

### Term Spread

```{r}
renderHighchart({
  highchart(type = "stock") %>%
  hc_title(text = "Term Spread between maturities") %>%
  hc_add_series(Term_Spread(),
                name = "Term Spread",
                color = "cornflowerblue") %>%
  hc_yAxis(title = list(text = "Term Spread (%)"),
           opposite = FALSE, 
           plotLines = list(list(value = 0, color = "red", width = 2,
                                 dashStyle = "shortdash"))) %>%
  hc_navigator(enabled = TRUE) %>%
  hc_scrollbar(enabled = FALSE) %>%
  hc_add_theme(hc_theme_flat()) %>%
  hc_exporting(enabled = TRUE)
})
```